/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 audi_r8.glb
Author: Aditya Graphical (https://sketchfab.com/Adityakm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/audi-r8-d10f75f74355452f8e417cc36f253841
Title: Audi R8
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/audi_r8.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <group position={[24, 21.6, 36.43]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['bonnet_Material_#22_0'].geometry} material={materials.Material_22} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[24.3, 21.63, -24.61]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object004_Material_#22_0'].geometry} material={materials.Material_22} position={[-60.8, 0, 1.01]} />
        </group>
        <group position={[24, 21.6, 36.43]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object005_Material_#22_0'].geometry} material={materials.Material_22} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[24.93, 21.44, 5.94]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object006_Material_#25_0'].geometry} material={materials.Material_25} position={[-30.26, 0, 2.41]} />
        </group>
        <group position={[24.88, 21.44, 5.94]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object007_Material_#22_0'].geometry} material={materials.Material_22} position={[-30.26, 0, 2.41]} />
        </group>
        <group position={[24.93, 21.44, 5.94]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object008_Material_#22_0'].geometry} material={materials.Material_22} position={[-30.26, 0, 2.41]} />
        </group>
        <group position={[24.93, 21.44, 5.94]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object010_Material_#22_0'].geometry} material={materials.Material_22} position={[-30.26, 0, 2.41]} />
        </group>
        <group position={[24, 21.6, 36.43]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object011_Material_#22_0'].geometry} material={materials.Material_22} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[24.3, 21.63, -24.61]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object012_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-60.8, 0, 1.01]} />
        </group>
        <group position={[24.93, 21.44, 5.94]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object013_Material_#25_0'].geometry} material={materials.Material_25} position={[-30.26, 0, 2.41]} />
        </group>
        <group position={[24, 21.6, 36.43]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object014_Material_#25_0'].geometry} material={materials.Material_25} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[24.3, 21.63, -24.61]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object015_Material_#25_0'].geometry} material={materials.Material_25} position={[-60.8, 0, 1.01]} />
        </group>
        <group position={[24, 21.6, 36.43]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object016_Material_#25_0'].geometry} material={materials.Material_25} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[24, 21.6, 36.44]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object017_Material_#25_0'].geometry} material={materials.Material_25} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[-7.8, 13.22, 62.53]} rotation={[-0.25, 0, 0]} scale={[1, 0.97, 0.78]}>
          <mesh geometry={nodes['Object027_Material_#25_0'].geometry} material={materials.Material_25} position={[14.34, 0.24, 0.05]} />
        </group>
        <group position={[24, 21.6, 36.43]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object028_Material_#22_0'].geometry} material={materials.Material_22} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[24, 21.6, 36.43]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object029_Material_#25_0'].geometry} material={materials.Material_25} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[24, 21.6, 36.43]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object030_Material_#25_0'].geometry} material={materials.Material_25} position={[0.23, -0.34, 3.34]} />
        </group>
        <group position={[24.88, 21.44, 5.94]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object031_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-30.26, 0, 2.41]} />
        </group>
        <group position={[24.93, 21.44, 5.94]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object032_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-30.26, 0, 2.41]} />
        </group>
        <group position={[-24.5, 10.57, -41.99]} rotation={[-1.55, 0, Math.PI / 2]} scale={0.84}>
          <mesh geometry={nodes['Object003_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[4.13, -67.69, -12.39]} />
        </group>
        <group position={[23.62, 10.45, -41.38]} rotation={[-1.88, Math.PI / 2, 0]} scale={0.97}>
          <mesh geometry={nodes['Circle005_Material_#26_0'].geometry} material={materials.Material_26} position={[-3.33, 4.2, 0]} />
        </group>
        <group position={[-0.21, 19.16, 61.93]} rotation={[-1.05, 0, 0]} scale={0.14}>
          <mesh geometry={nodes['Cylinder002_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-10.39, 0, 0]} />
        </group>
        <group position={[-0.21, 24.6, -60.42]} rotation={[-2.61, 0, 0]} scale={0.14}>
          <mesh geometry={nodes['Cylinder003_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-10.39, 0, 0]} />
        </group>
        <group position={[-24.32, 10.53, 34.32]} rotation={[2.49, 0, Math.PI / 2]} scale={0.82}>
          <mesh geometry={nodes['Object045_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[6.43, -68.2, -13.75]} />
        </group>
        <group position={[26.37, 10.27, 36.08]} rotation={[2.49, 0, Math.PI / 2]} scale={0.82}>
          <mesh geometry={nodes['Object034_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.37, 10.27, 36.08]} rotation={[2.49, 0, Math.PI / 2]} scale={0.82}>
          <mesh geometry={nodes['Object050_Material_#25_0'].geometry} material={materials.Material_25} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.37, 10.27, 36.08]} rotation={[2.49, 0, Math.PI / 2]} scale={0.82}>
          <mesh geometry={nodes['Object051_Material_#31_0'].geometry} material={materials.Material_31} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.37, 10.27, 36.08]} rotation={[2.49, 0, Math.PI / 2]} scale={0.82}>
          <mesh geometry={nodes['Object052_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.72, 10.43, -41.36]} rotation={[-1.55, 0, Math.PI / 2]} scale={0.84}>
          <mesh geometry={nodes['Object053_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.72, 10.43, -41.36]} rotation={[-1.55, 0, Math.PI / 2]} scale={0.84}>
          <mesh geometry={nodes['Object054_Material_#25_0'].geometry} material={materials.Material_25} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.72, 10.43, -41.36]} rotation={[-1.55, 0, Math.PI / 2]} scale={0.84}>
          <mesh geometry={nodes['Object055_Material_#32_0'].geometry} material={materials.Material_32} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[-27.1, 10.43, -41.36]} rotation={[1.59, 0, -Math.PI / 2]} scale={[-0.84, 0.84, 0.84]}>
          <mesh geometry={nodes['Object056_Material_#25_0'].geometry} material={materials.Material_25} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.72, 10.43, -41.36]} rotation={[-1.55, 0, Math.PI / 2]} scale={0.84}>
          <mesh geometry={nodes['Object057_Material_#29_0'].geometry} material={materials.Material_29} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.72, 10.43, -41.36]} rotation={[-1.55, 0, Math.PI / 2]} scale={0.84}>
          <mesh geometry={nodes['Object058_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.37, 10.27, 36.08]} rotation={[2.49, 0, Math.PI / 2]} scale={0.82}>
          <mesh geometry={nodes['Object059_Material_#25_0'].geometry} material={materials.Material_25} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[26.37, 10.27, 36.08]} rotation={[2.49, 0, Math.PI / 2]} scale={0.82}>
          <mesh geometry={nodes['Object060_Material_#30_0'].geometry} material={materials.Material_30} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[18.38, 17.43, 56.33]} rotation={[3.09, 0.85, 1.67]}>
          <mesh geometry={nodes['Object048_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[2.09, 0.45, -7.02]} />
        </group>
        <group position={[24.06, 21.55, 36.5]} rotation={[3.09, 0.85, 1.67]}>
          <mesh geometry={nodes['Box014_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[6.02, -10.98, -24.24]} />
        </group>
        <group position={[17.74, 17.27, 54.81]} rotation={[3.09, 0.85, 1.67]}>
          <mesh geometry={nodes['Object061_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[1.84, -1.09, -7.55]} />
        </group>
        <group position={[17.74, 17.27, 54.81]} rotation={[3.09, 0.85, 1.67]}>
          <mesh geometry={nodes['Object062_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[1.84, -1.09, -7.55]} />
        </group>
        <group position={[17.74, 17.27, 54.81]} rotation={[3.09, 0.85, 1.67]}>
          <mesh geometry={nodes['Object063_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[1.84, -1.09, -7.55]} />
        </group>
        <group position={[17.74, 17.27, 54.81]} rotation={[3.09, 0.85, 1.67]}>
          <mesh geometry={nodes['Object064_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[1.84, -1.09, -7.55]} />
        </group>
        <group position={[17.74, 17.27, 54.81]} rotation={[3.09, 0.85, 1.67]}>
          <mesh geometry={nodes['Object065_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[1.84, -1.09, -7.55]} />
        </group>
        <group position={[13.14, 15.35, 60.9]} rotation={[3.09, 0.85, 1.67]} scale={1.1}>
          <mesh geometry={nodes['Object066_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-0.21, 0.59, -0.14]} />
        </group>
        <group position={[-24.56, 21.6, 36.43]} rotation={[3.09, -0.85, -1.67]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes['Box013_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[6.02, -10.98, -24.24]} />
        </group>
        <group position={[-24.56, 21.6, 36.43]} rotation={[3.09, -0.85, -1.67]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes['Object047_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[6.02, -10.98, -24.24]} />
        </group>
        <group position={[-24.56, 21.6, 36.43]} rotation={[3.09, -0.85, -1.67]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes['Object044_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[6.02, -10.98, -24.24]} />
        </group>
        <group position={[17.79, 23.37, -56.83]} rotation={[0.01, Math.PI / 2, 0]}>
          <mesh geometry={nodes['Object067_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-93.06, -1.54, 9.54]} />
        </group>
        <group position={[-18.27, 23.37, -56.83]} rotation={[-3.14, -Math.PI / 2, 0]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes['Object068_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-93.06, -1.54, 9.54]} />
        </group>
        <group position={[26.72, 10.43, -41.36]} rotation={[-1.55, 0, Math.PI / 2]} scale={0.84}>
          <mesh geometry={nodes['Object069_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[4.88, -6.54, -12.24]} />
        </group>
        <group position={[-26.66, 26.14, 20.67]} rotation={[-Math.PI / 2, 0, 0]} scale={0.73}>
          <mesh geometry={nodes['Object001_Material_#22_0'].geometry} material={materials.Material_22} position={[38.85, 23.84, 246.57]} />
        </group>
        <group position={[-26.66, 26.14, 20.67]} rotation={[-Math.PI / 2, 0, 0]} scale={0.73}>
          <mesh geometry={nodes.Object074_wire_141007058_0.geometry} material={materials.wire_141007058} position={[38.85, 23.84, 246.57]} />
        </group>
        <group position={[-26.66, 26.14, 20.67]} rotation={[-Math.PI / 2, 0, 0]} scale={0.73}>
          <mesh geometry={nodes.Object075_wire_141007058_0.geometry} material={materials.wire_141007058} position={[38.85, 23.84, 246.57]} />
        </group>
        <group position={[26.09, 26.14, 20.67]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.73, 0.73, 0.73]}>
          <mesh geometry={nodes['Object076_Material_#22_0'].geometry} material={materials.Material_22} position={[38.85, 23.84, 246.57]} />
        </group>
        <group position={[26.09, 26.14, 20.67]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.73, 0.73, 0.73]}>
          <mesh geometry={nodes.Object077_wire_141007058_0.geometry} material={materials.wire_141007058} position={[38.85, 23.84, 246.57]} />
        </group>
        <group position={[26.09, 26.14, 20.67]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.73, 0.73, 0.73]}>
          <mesh geometry={nodes.Object078_wire_141007058_0.geometry} material={materials.wire_141007058} position={[38.85, 23.84, 246.57]} />
        </group>
        <group position={[-24.32, 10.53, 34.32]} rotation={[2.49, 0, Math.PI / 2]} scale={0.82}>
          <mesh geometry={nodes['Object079_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[6.43, -68.2, -13.75]} />
        </group>
        <group position={[-26.92, 10.35, 36.04]} rotation={[-2.14, -1.56, -2.02]} scale={0.05}>
          <mesh geometry={nodes['Cylinder011_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-10.39, 0, 0]} />
        </group>
        <mesh geometry={nodes['Object018_Material_#25_0'].geometry} material={materials.Material_25} position={[-0.25, 14.57, 62.56]} rotation={[-0.12, 0, -Math.PI / 2]} scale={[1.44, 0.96, 0.69]} />
        <mesh geometry={nodes['Plane006_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-0.16, 13.79, 64.13]} rotation={[-0.2, 0, 0]} />
        <mesh geometry={nodes['Text001_Material_#25_0'].geometry} material={materials.Material_25} position={[-0.18, 13.09, 64.35]} rotation={[-0.2, 0, 0]} />
        <mesh geometry={nodes['Text002_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[8.7, 23.71, -60.31]} rotation={[-2.6, 0.14, 3.1]} scale={0.01} />
        <mesh geometry={nodes['Plane008_Material_#25_0'].geometry} material={materials.Material_25} position={[-0.64, 8.96, -5.56]} rotation={[-1.56, 0, 0]} />
        <mesh geometry={nodes.Cylinder004__0.geometry} material={materials.Cylinder004__0} position={[-20.89, 12.07, -60.32]} rotation={[0, 0.44, 0]} scale={0.95} />
        <mesh geometry={nodes.Cylinder005__0.geometry} material={materials.Cylinder004__0} position={[-18.43, 12.06, -61.36]} rotation={[0, 0.46, 0]} scale={0.95} />
        <mesh geometry={nodes.Cylinder006__0.geometry} material={materials.Cylinder004__0} position={[20.45, 12.07, -60.32]} rotation={[-Math.PI, 0.44, 0]} scale={[-0.95, 0.95, 0.95]} />
        <mesh geometry={nodes.Cylinder007__0.geometry} material={materials.Cylinder004__0} position={[17.99, 12.06, -61.36]} rotation={[-Math.PI, 0.46, 0]} scale={[-0.95, 0.95, 0.95]} />
        <mesh geometry={nodes['Plane009_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-0.3, 19.63, -60.65]} rotation={[-2.73, 0, -Math.PI]} />
        <mesh geometry={nodes['Text003_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-0.27, 18.99, -61.02]} rotation={[-2.73, 0, -Math.PI]} />
        <mesh geometry={nodes.Object070__0.geometry} material={materials.Cylinder004__0} position={[-18.43, 12.06, -61.36]} rotation={[0, 0.46, 0]} scale={0.95} />
        <mesh geometry={nodes.Object071__0.geometry} material={materials.Cylinder004__0} position={[-20.89, 12.07, -60.32]} rotation={[0, 0.44, 0]} scale={0.95} />
        <mesh geometry={nodes.Object072__0.geometry} material={materials.Cylinder004__0} position={[17.99, 12.06, -61.36]} rotation={[0, -0.46, 0]} scale={[-0.95, 0.95, 0.95]} />
        <mesh geometry={nodes.Object073__0.geometry} material={materials.Cylinder004__0} position={[20.45, 12.07, -60.32]} rotation={[0, -0.44, 0]} scale={[-0.95, 0.95, 0.95]} />
        <mesh geometry={nodes['Object080_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[8.7, 23.71, -60.31]} rotation={[-2.6, 0.14, 3.1]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/audi_r8.glb')
